### PR TITLE
Review/michaelbassett/tristankindig

### PR DESCRIPTION
**Pull request by TristanKindig**
test/sync.js
‘filesMatchNameandSize’
you could add another test, in which you check whether the function returns false for non-matching lists of the same name

test/base64utils.js
‘writeBase64Encoded’
the function on line 41 looks a little cluttered, just from a readability perspective. I understand the appeal of concise code, so if this is convention then just ignore. But if not I would suggest that you consider expanding it out into a more familiar format that is easier to read quickly.

index.js
we were supposed to refactor the checkForChanges() function and functions related to Pipeline into other files. Jules chose to put them into a file called “lib/sync/sync-driver” but it doesn’t really matter where so long as they are no longer here.

this is perhaps related to the previous comment, because I think if a function is in index.js it is difficult to test directly: you didn’t test chcekForChanges(). This is an issue because it performs the operations at the heart of the dropbox implementation.

dropboxuris.js
‘getPath’
I’m not sure whether it’s good practice to test how a function behaves when it fails. If it is, though, I’d suggest that you consider a unit test in which you provide the function with invalid input and then confirm that it fails in the expected manner. Just because it’s an important function that’s close to the user in terms of the program’s workflow.

### CODE REVIEW

**Comment by bassettmb** [comment]
Nothing was changed. No need to add comments to this branch, especially since the merge is not a fast-forward.

**Comment by TristanKindig** [comment]
> No need to add comments to this branch, especially since the merge is not
a fast-forward.

Could you explain what you mean by this?

Also, slightly off-topic: might you be willing to help me debug my code
sometime today? I've been struggling with even the base assignment, and
implementing the pull requests is another matter entirely. Just going for a
shot in the dark here, haha.

Tristan

**Comment by bassettmb** [comment]
If the merge is a fast-forward, then there are no merge conflicts and git can automatically apply the changes without human intervention. The comments added would have to be manually merged in since you applied your changes against the original head of the branch which doesn't have the changes from the other pull request. Since there were no changes that directly alter the behavior of the code, I got lazy and opted to just close it.

I may be able to help you, but I have other commitments presently. I'll take a look at it, though.

**Comment by TristanKindig** [comment]
I'm working on it at the moment. I expect to have it up and running in an
hour or so. I'll let you know when it's in a respectable state, so that you
aren't wasting your time fixing errors that I'm fixing now

**Comment by TristanKindig** [comment]
And if you can't, that's totally fine. I appreciate that you're even
considering trying honestly

**Pull request closed without merging**
